apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ps1x0ts1d-java-quarkus
  janus-idp.io/tekton: ps1x0ts1d-java-quarkus
  backstage.io/kubernetes-id: ps1x0ts1d-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ps1x0ts1d-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
