apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ps1x0ts1d-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ps1x0ts1d-java-quarkus-gitops